name: Plugin - Create  Pull Request

on:
  workflow_dispatch:
    inputs:
      SOURCE_BRANCH:
        description: "From branch for PR"
        required: true
        default: "staging"
      TARGET_BRANCH:
        description: "Target branch for PR"
        required: true
        default: "main"

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create PR
        run: |
          gh pr create \
            --base "${{ github.event.inputs.TARGET_BRANCH }}" \
            --head "${{ github.event.inputs.SOURCE_BRANCH }}" \
            --title "Automated PR: ${{ github.event.inputs.SOURCE_BRANCH }} â†’ ${{ github.event.inputs.TARGET_BRANCH }}" \
            --body "This PR was created by CI to merge changes from **${{ github.event.inputs.SOURCE_BRANCH }}** into **${{ github.event.inputs.TARGET_BRANCH }}**."
